name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --build-arg releasever=8 --file Dockerfile --tag uuzrepo/rpmbuild-centos:8
    
    - name: docker login 
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWD}}
      
    - name: docker push
      run: docker push uuzrepo/rpmbuild-centos:8
